databases:
  - name: ilyass
    databaseName: ilyass
    user: ilyass

services:
  - type: web
    name: Budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ilyass
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
